spring:
  application:
    name: Order-Service
  profiles:
    active: local
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
server:
  port: 8082
user:
  service:
    url: http://localhost:8080