spring:
  application:
    name: Order-Service
  profiles:
    active: local
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: ${SERVER_PORT:8082}

user:
  service:
    url: ${USER_SERVICE_URL:http://user-service:8080}