apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          startupProbe:
            tcpSocket:
              port: 2181
            failureThreshold: 60
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 0
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3